// <auto-generated />
namespace Gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10));
        
        string IMigrationMetadata.Id
        {
            get { return "202104281135582_10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
