// <auto-generated />
namespace Grades.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_authorizationLogic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_authorizationLogic));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091433392_change_authorizationLogic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
